### ISSUE TITLE
SHP files don't import into Google Earth correctly. 

### ISSUE THREAD

**Issue by dahifi** [vapublicaccessproject/va-precinct-maps-2016#4]
Precincts show up about 30 miles too far north when importing into Google Earth. 

From elsewhere: Google Maps Engine works with WGS84 EPSG-Code 4326, so you'll need to project the shapefile into the correct projection.

**Comment by jalbertbowden** [comment]
preach! why wgs84 isn't default for state data is beyond me. would be nice to see some standards adoption vs. having to edit datasets before you can ever use them.
